version: '3.7'

services:
  apisix:
    image: apache/apisix:latest
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080
  npm:
        image: 'jc21/nginx-proxy-manager:latest'
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data/nginx_proxy_manager/data:/data
            - ./data/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
        restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak123
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db

  keycloak_db:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
    volumes:
      - ./keycloak_db_data:/var/lib/postgresql/data
  order_service:
    build:
      context: ./order
      dockerfile: Dockerfile
    env_file: ./order/.env
    ports:
      - 3000:3000
  product_service:
    build:
      context: ./product
      dockerfile: Dockerfile
    env_file: ./product/.env
    ports:
      - 3001:3000

volumes:
  etcd_data:
    driver: local

networks:
  apisix:
    driver: bridge